# Generated by Django 6.0.6 on 2026-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('standard', 'Стандарт'), ('superior', 'Полулюкс'), ('suite', 'Люкс')], max_length=20, verbose_name='Тип номера')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('occupied', 'Занят'), ('reserved', 'Забронирован')], default='available', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
