# Generated by Django 6.0.6 on 2026-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active_client_is_staff_client_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='admin', max_length=150, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
