# Generated by Django 6.0.6 on 2026-06-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_username_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='password_hash',
            new_name='password',
        ),
    ]
