# Generated by Django 6.0.6 on 2026-06-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('reservation_status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('checked_in', 'Заселён'), ('checked_out', 'Выселен'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус бронирования')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank', 'Банковский перевод'), ('online', 'Онлайн')], max_length=20, verbose_name='Метод оплаты')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('failed', 'Неудачно'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='Время заезда')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to='clients.client', verbose_name='Клиент')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='reservations.reservation', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Проживающий',
                'verbose_name_plural': 'Проживающие',
            },
        ),
    ]
